name: macOS
on:
  push:
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        runner:
          - macos-latest
        ocaml-compiler:
          - 5.5.0
    name: >-
      OCaml ${{ matrix.ocaml-compiler }}, macOS arm64
    runs-on: ${{ matrix.runner }}
    steps:
    - name: Install dependencies
      run: brew install gcc
    - name: Content
      run: |
        set -x
        find $(brew --prefix gcc)
