name: macOS
on:
  push:
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        runner:
          - macos-latest
        ocaml-compiler:
          - 5.5.0
    name: >-
      OCaml ${{ matrix.ocaml-compiler }}, macOS arm64
    runs-on: ${{ matrix.runner }}
    steps:
    - name: Content before
      run: |
        find /opt/homebrew
    - name: Install dependencies
      run: brew install gcc
    - name: Content after
      run: |
        find /opt/homebrew
    - name: which
      run: |
        set -x
        gcc -dumpmachine
        aarch64-linux-gnu-gcc -dumpmachine || echo Error: $?
        aarch64-pc-linux-gnu-gcc -dumpmachine || echo Error: $?
        x86_64-pc-linux-gnu-gcc -dumpmachine || echo Error: $?
