name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        ocaml-compiler: [5.0.0]
    name: OCaml ${{ matrix.ocaml-compiler }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
        opam-local-packages: |
          *.opam
          !ocaml-solo5-cross-aarch64.opam
    - name: Install ocaml-solo5 and dune
      run: opam install ocaml-solo5 conf-libseccomp dune
    - name: Compile example with hvt
      run: MODE=hvt opam exec -- dune build --root example
    - name: Compile example with spt
      run: MODE=spt opam exec -- dune build --root example
    - name: Run example with spt
      run: opam exec -- solo5-spt example/_build/solo5/main.exe
    - name: Compile example with virtio
      run: MODE=virtio opam exec -- dune build --root example
    - name: Compile example with muen
      run: MODE=muen opam exec -- dune build --root example
    - name: Compile example with xen
      run: MODE=xen opam exec -- dune build --root example
