name: Test
on:
  push:
  pull_request:
jobs:
  macos:
    name: macOS aarch64 cross-compiler
    runs-on: macos-latest
    env:
      OPAMYES: 1
    steps:
    - uses: actions/checkout@v7
    - uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 5.4.1
        opam-pin: false
    - name: Build dependencies
      run: |
        opam pin add -n solo5-cross-aarch64 git+https://github.com/samoht/solo5.git#macos
        opam install solo5-cross-aarch64 ocamlfind ocaml-src opatch
    - name: Build OCaml/Solo5
      run: |
        set -x
        eval $(opam env)
        pfx="$(opam var prefix)"
        ./configure.sh --prefix="$pfx" \
          --sysroot="$pfx/lib/ocaml-solo5" \
          --target=aarch64-solo5-none-static \
          --othertoolprefix=llvm- \
          --ocaml-configure-option=--disable-function-sections
        export __V=1
        make V=1 -j2
        make install
